Make our browser testing much faster
We were using playwright essentially to unit test the js version of the
sdk in actual browser engines.

We can get the same effect, but much faster, with vitest browser
mode*

This takes our tests from 32s on my computer down to about 6s.

It also means we don't have to do this page.evaluate thing and
serialize things across the page boundary over and over, which was a pain.

Now that we're not using page.evaluate it's exposed a lot more type
errors if your editor shows them. Fixing this seemed a little out of
scope since we don't check anyway and the tests pass, but I'd like to
come back to it in the future.

A big part of the reason this is faster is only initializing one sqlite
db and resetting it per test. I tried applying just this fix to the
playwright version and it also sped things up a fair bit, from 21s
(for just the sqlite tests) to 8.35s. But that's still slower overall,
and I think not having to do the page.evaluate stuff is a big quality of
life improvement.

Something about the vitest packages being added caused tsc to fail with
this error:

```
Cannot find module 'assertion-
  error'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the
  'paths' option?

import { AssertionError as ImportedAssertionError } from "assertion-error";
```

Changing moduleResolution to node fixes this. It appears to me from
reading that without this we are getting "classic"†, which is apparently
not to be used‡.

* https://vitest.dev/guide/browser/
† https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-is-host-defined
‡ https://www.typescriptlang.org/docs/handbook/modules/reference.html#classic